name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore **/*.csproj
    - name: Build
      run: dotnet build --no-restore **/*.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal **/*UnitTests/*.csproj
